/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="data.d.ts" />
/// <reference path="rule.d.ts" />
/// <reference path="xiangting.d.ts" />
/// <reference path="hule.d.ts" />
/// <reference path="message.d.ts" />
/// <reference path="shoupai.d.ts" />
/// <reference path="shan.d.ts" />
/// <reference path="he.d.ts" />
/// <reference path="game.d.ts" />
/// <reference path="boardinfo.d.ts" />
/// <reference path="board.d.ts" />
